print("hello World Strings".capitalize())
print("hello World Strings".casefold())
print("hello world strings".center(50))
print("hello world strings".count("world"))
print("hello World Strings".encode(encoding="ascii"))
print("hello World Strings".endswith("s"))
print("hello\t World\t Strings".expandtabs(50))
print("hello World Strings".find("Wo"))
print("hello World {percentage:%} Strings".format(percentage=50))
print("hello World Strings".index("S"))